### ISSUE TITLE
Food for thought: a tool to purge Twitter account

### ISSUE THREAD

**Issue by marcin-rzeznicki** [travisbrown/cancel-culture#5]
Someone gave me the link to your repo so sorry if my understanding of this project or your goals is laughable. But in all honestly, I believe that the ultimate move to get rid of all the harmful stuff you describe is to delete the account. I've never had a Twitter account myself - but almost every time someone gave ma a link to "check out" it was a bumpy ride through controversy, contempt or, at the very least, irrelevant trivia. In my personal opinion, this is no coincidence. Twitter (at best inadvertently) lives off attitudes that increase users' engagement, and it's more often the negative things that pump it up. Therefore, you might consider adding such a tool to the suite - at the very least it can serve as a reminder to your users that there is a way out.

**Comment by travisbrown** [comment]
Twitter often plays an important professional and personal role in people's lives. Deleting your Twitter account because of harassment might be the reasonable thing to do in extreme cases, but it's well-supported by Twitter's own interface, and is pretty far from the goal of this project (which is to help people fight harassment by giving them tools for identifying and documenting it).
